### ISSUE TITLE
E5 - Browse Events by Date displays in wrong order (most recent should be at top)

### ISSUE THREAD

**Issue by mmafe** [brharp/hjckrrh#143]
Browse Events by Date displays in wrong order (most recent should be at top)

**Comment by mmafe** [comment]
Fixed as part of hotfix_20150807.3.0

**Comment by jpinsent** [comment]
This does not appear to have been fixed. Most recent is still being displayed at the bottom.

![e5 problem](https://cloud.githubusercontent.com/assets/12450480/9274453/facaf4ea-4263-11e5-868e-a9362db00b72.PNG)

**Comment by mmafe** [comment]
Are you seeing this on AODADemo or OAC?

OAC is currently overridden, so they won't see the change unless we revert.

**Comment by jpinsent** [comment]
@mmafe I'm currently looking at it on the AODADemo website. I am still seeing the events sorted in reverse chronological order on the following pages:

https://aoda.web.uoguelph.ca/oac/events/upcoming

https://aoda.web.uoguelph.ca/oac/events/archive

**Comment by mmafe** [comment]
Those links are both oac ;)

**Comment by jpinsent** [comment]
@mmafe Oh! My bad, I was thinking that AODADemo meant the aoda.web address and OAC meant the live site. WHOOPS. That makes a lot more sense now, haha.

This is confirmed working on the AODA Demo site.

![events view fix](https://cloud.githubusercontent.com/assets/12450480/9274790/89e78628-4266-11e5-9188-0d7dc751e448.PNG)

**Comment by mmafe** [comment]
No worries! ^_^
